### ISSUE TITLE
Startup crash on KDE with UnhandledPromiseRejectionWarning 

### ISSUE THREAD

**Issue by drps** [cucumber-sp/yandex-music-linux#42]
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

```bash
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.2.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 13.5 ГиБ of RAM
Graphics Processor: RENOIR
```

```bash
$ yandexmusic --trace-warnings
08:34:40.582 (Application)    › Version: 5.0.10
08:34:40.583 (Application)    › Build: 5.0.10 (release-beta-10/b1ebaba6)
08:34:40.586 (SingleInstance)    › Single instance
(node:26653) UnhandledPromiseRejectionWarning: Error: Failed to load image from path 'build/next-desktop/favicon.png'
    at createTray (/usr/lib/yandexmusic/yandexmusic.asar/main/lib/createTray.js:4:16)
    at /usr/lib/yandexmusic/yandexmusic.asar/main/index.js:34:5
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:26653) Error: Failed to load image from path 'build/next-desktop/favicon.png'
    at createTray (/usr/lib/yandexmusic/yandexmusic.asar/main/lib/createTray.js:4:16)
    at /usr/lib/yandexmusic/yandexmusic.asar/main/index.js:34:5
```

**Comment by Maks1mS** [comment]
Аналогично. Похоже проблема появилась после 9b67fe0c60813d0436492c55a8c587b6c1bf1901

**Comment by cucumber-sp** [comment]
Исправлено в https://github.com/cucumber-sp/yandex-music-linux/commit/3eb7fe7816733cf8a62d139d55e57cfe659fbc7a
